# Generated by Django 3.2 on 2023-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='email address')),
                ('email_code', models.CharField(default=None, max_length=10)),
                ('email_code_updated', models.DateTimeField(default=None, null=True)),
                ('img_code', models.CharField(default=None, max_length=10)),
                ('img_code_updated', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'verify_token',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='EmailToken',
        ),
    ]
