# Generated by Django 3.2 on 2023-05-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230518_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifytoken',
            name='email_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verifytoken',
            name='img_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
